### ISSUE TITLE
Seems like newer Files can't be exported anymore?

### ISSUE THREAD

**Issue by EtzBetz** [kytulendu/Gw2Browser#2] opened 2017-08-19 20:37 UTC
I tried this new version again today and it seems like I can't export any newer files. When I right click on any file and then click on either export option, the window just plain closes without any error. Is that an error on my end or does that happen to everyone here?

Also, is there a way of showing all files just arranged on id, without any folders? That would help to just see and export new files and then looking through them.

Thanks, this program is just great!
Greetings, Raphael

**Comment by kytulendu** [comment] 2017-08-21 08:25
Likely it cause by 3rd program on your Windows installation that modify the appearance of window that not compatible with wxWidgets...
Try to run Gw2Browser on other PC you have or friend's PC and see if it work or not.
But to be sure, could you give me the file id that cause the problem?

And yes, there is a way, but I have to code it :P 
I have some ideas like that, by using drop down box is for choosing type of file to display in list control, the list control will have file id, file type, file size and can be sorted like typical file browser.
For now, I have no motive to do it since that will require rewrite large part of CategoryTree class, which is one of the big class in GW2Browser.

**Comment by EtzBetz** [comment] 2017-09-16 18:57
Sorry for responding this late, I didn't receive any updates and forgot about it.
So, I tried it in a quite fresh VM and tried to export a Image(1770664). When I do that, it crashes just like any other newer file.

Is using a VM a problem too?

Greetings, Raphael

**Comment by kytulendu** [comment] 2017-09-17 14:53
I have test it on my machine and found that it crash when I try to export a file as the browser display save file dialog. It seems it was cause by wxWidgets 3.1.0, I have try to update wxWidgets with latest release version, [wxWidgets 3.0.3.1](https://github.com/wxWidgets/wxWidgets/releases), and found that the crash problem is gone. (it may crash at first time, after that it work on both my Windows 10 PC and Windows 7 laptop)

I have committed the change to master branch, try update and rebuild wxWidgets with **wxWidgets 3.0.3.1** then update Gw2Browser source code and rebuild it to see if the problem is fix on your PC.

I also update the compile guide on GitHub main page (readme file) according to new changes.

**Comment by kytulendu** [comment] 2018-01-23 00:07
I have test export files with the new gw2browser binary (1.0.9.0-dev2) on my Windows 7 laptop and 3 other difference PC on my workplace (one is Windows 10 and 2 is Windows 7) and haven't encounter file dialog crash problem, so I assume it safe to close this issue for now.

**Closed as completed by kytulendu** 2018-01-23 00:07 UTC
